title: "CodyMKW"
description: "Just Cody's little page on the interwebz! :)"
url: "https://codymkw.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap

# Include files
include:
  - _pages
  - blogdata