const weapons = [
  ".52 Gal",
  ".96 Gal",
  ".96 Gal Deco",
  "Aerospray MG",
  "Aerospray RG",
  "Ballpoint Splatling",
  "Bamboozler 14 Mk I",
  "Big Swig Roller",
  "Blaster",
  "Bloblobber",
  "Carbon Roller",
  "Carbon Roler Deco",
  "Clash Blaster",
  "Clash Blaster Neo",
  "Classic Squiffer",
  "Custom Jet Squelcher",
  "Custom Splattershot Jr.",
  "Dapple Dualies",
  "Dapple Dualies Nouveau",
  "Dark Tetra Dualies",
  "Dualie Squelchers",
  "Dynamo Roller",
  "E-liter 4K",
  "E-liter 4K Scope",
  "Explosher",
  "Flingza Roller",
  "Forge Splattershot Pro",
  "Glooga Dualies",
  "Goo Tuber",
  "H-3 Nozzlenose",
  "Heavy Splatling",
  "Hero Shot Replica",
  "Hydra Splatling",
  "Inkbrush",
  "Inkbrush Nouveau",
  "Jet Squelcher",
  "Krak-On Splat Roller",
  "L-3 Nozzlenose",
  "L-3 Nozzlenose D",
  "Luna Blaster",
  "Luna Blaster Neo",
  "Mini Spatling ",
  "N-ZAP '85",
  "N-ZAP '89",
  "Nautilus 47",
  "Neo Splash-o-matic",
  "Neo Sploosh-o-matic",
  "Octobrush",
  "Range Blaster",
  "Rapid Blaster",
  "Rapid Blaster Deco",
  "Rapid Blaster Pro",
  "REEF-LUX 450",
  "Slosher",
  "Slosher Deco",
  "Sloshing Machine",
  "Snipewriter 5H",
  "Splash-o-matic",
  "Splat Brella",
  "Splat Charger",
  "Splat Dualies",
  "Splat Roller",
  "Splatana Stamper",
  "Splatana Wiper",
  "Splatterscope",
  "Splattershot",
  "Splattershot Jr.",
  "Splattershot Nova",
  "Splattershot Pro",
  "Sploosh-o-matic",
  "Squeezer",
  "Tenta Brella",
  "Tentatek Splattershot",
  "Tri-Slosher",
  "Tri-Slosher Nouveau",
  "Tri-Stringer",
  "Z+F Splat Charger",
  "Z+F Splatterscope",
  "Zink Mini Splatling",
  "Painbrush",
  "S-Blast '92",
  "Tenta Sorella Brella",
  "Custom Duelie Squelchers",
  "Light Tetra Duelies",
  "Heavy Splatling Deco",
  "H-3 Nozzlenose D",
  "Rapid Blaster Pro Deco",
  "Splatana Wiper Deco",
  "Annaki Splattershot Nova",
  "Big Swig Roller Express",
  "Dread Wringer",
  "Heavy Edit Splatling",
  "Gold Dynamo Roller",
  "Octobrush Nouveau",
  "Custom Goo Tuber",
  "Sloshing Machine Neo",
  "Bloblobber Deco",
  "Ballpoint Splatling Nouveau",
  "Sorella Brella",
  "Inkline Tri-Stringer"
];

const headgears = [
  "18K Aviators",
  "360 All-Scopes",
  "Air Gills DX",
  "Annaki Beret",
  "Annaki Beret & Glasses",
  "Annaki Charms",
  "Annaki Mask",
  "Armor Helmet Replica",
  "Astro Helm",
  "B-ball Headband",
  "Backward Cap",
  "Bamboo Hat",
  "Beachcomber",
  "Bike Helmet",
  "Black Arrowbands",
  "BlobMob Mask",
  "Blowfish Bell Hat",
  "Bobble Hat",
  "Boss Floss",
  "Brain Strainer",
  "Bream-Brim Cap",
  "Bucket Hat",
  "Camo Mesh",
  "Camping Hat",
  "Chaos Helm",
  "Cephalo Pods",
  "Classic Bowler",
  "Classic Straw Boater",
  "Cycle King Cap",
  "Cycling Cap",
  "Deep Sinker Helm",
  "Designer Headphones",
  "Double Egg Shades",
  "Dust Blocker 2000",
  "Dustcloud 'Phones",
  "Dustcloud Cap",
  "Enchanted Hat",
  "Face Visor",
  "Fake Contacts",
  "Firefin Facemask",
  "FishFry Biscuit Bandana",
  "FishFry Visor",
  "Five-Alarm Helmet",
  "Five-Panel Cap",
  "Forge Mask",
  "Fresh Fish Head",
  "Full-Moon Glasses",
  "Gas Mask",
  "Glassless Glasses",
  "Golf Visor",
  "Half-Rim Glasses",
  "Hat-Trick Bell Hat",
  "Headlamp Helmet",
  "Hero Headset Replica",
  "Hero Mindset Replica",
  "Hickory Work Cap",
  "Hipster Horn-Rims",
  "Hockey Helmet",
  "Home-Team Catcher",
  "House-Tag Denim Cap",
  "Howdy Hat",
  "Ink-Black Flap Cap",
  "Ink-Tinted Goggles",
  "Invisifloats",
  "Jellyvader Cap",
  "Jean Dream Bucket",
  "Jet Cap",
  "Jogging Headband",
  "Jungle Hat",
  "Knitted Hat",
  "Lightweight Cap",
  "Lo-Vis Visor",
  "Marinated Headphones",
  "Moto Shades",
  "MTB Helmet",
  "Ocho OctoPhones",
  "Ocho OctoPhones Blancos",
  "Octo Tackle Helmet Deco",
  "Octoglasses",
  "Octoking Facemask",
  "Paintball Mask",
  "Painter's Mask",
  "Paisley Bandana",
  "Party Hard Hat",
  "Pearlescent Crown L",
  "Pearlescent Crown S",
  "Pilot Goggles",
  "Power Mask Mk I",
  "Power Mask",
  "Retro BluFocals",
  "Retro Framers",
  "Retro Specs",
  "Safari Hat",
  "Samurai Helmet",
  "Scrum Cap",
  "Sea-Me-Nots",
  "Seafoam 'Phones",
  "Seafoam Cap",
  "Short Beanie",
  "Skate Helmet",
  "Skull Bandana",
  "Snorkel Mask",
  "Soccer Headband",
  "Special-Forces Beret",
  "Splash Goggles",
  "Sporty Bobble Hat",
  "Squash Headband",
  "Squid Clip-Ons",
  "Squid Facemask",
  "Squid Hairclip",
  "Squid Nordic",
  "Squid-Stitch Cap",
  "Squidband",
  "Squidbeak Shield",
  "Squidlife Headphones",
  "Squidvader Cap",
  "Squinja Mask Mk I",
  "Squinja Mask Mk II",
  "Stay Crusty Cap",
  "Stealth Goggles",
  "Steel Helm",
  "Straw Boater",
  "Streetstyle Cap",
  "Striped Beanie",
  "Studio Headphones",
  "Sun Visor",
  "Sushi Sous-Chef Band",
  "SV925 Circle Shades",
  "Swim Goggles",
  "Takoroka Mesh",
  "Takoroka Visor",
  "Teddy Band",
  "Tennis Headband",
  "Tentaclinger Earring",
  "Tinted Shades",
  "Toni Kensa Goggles",
  "Treasure Hunter",
  "Triple-Deck Specs",
  "Tulip Parasol",
  "Two-Stripe Mesh",
  "Urchins Cap",
  "Visor Skate Helmet",
  "Wharfside Cap",
  "White Arrowbands",
  "White Headband",
  "Winkle Stripe Helm",
  "Woolly Urchins Classic",
  "Z+F Flair Bowler",
  "ZedFry Beanie",
  "ZedFry Helmet",
  "Zekko Mesh",
  "Commander Cap",
  "Cap'n Cap",
  "Glam Clam Specs",
  "Crust Bucket Visor",
  "Barrelfish Home Helmet",
  "Stealth Squidbeak Shield",
  "See-an-Enemy HUD",
  "Retro Future Helmet",
  "Do-Rag, Cap & Glasses",
  "Seashell Bamboo Hat",
  "Noise Cancelers",
  "Headlamp Hat",
  "Swim Cap",
  "Urchin Understitch",
  "Aux Boxes",
  "Away-Team Catcher",
  "Welding Mask",
  "Cap of Legend",
  "3D Glasses"
];


const shirts = [
  "Airflow & Hustle Jacket",
  "Aloha Shirt",
  "Anchor Life Vest",
  "Anchor Sweat",
  "Annaki Blue Cuff",
  "Annaki Bracelet Tee",
  "Annaki Choker Tee",
  "Annaki Drive Tee",
  "Annaki Flannel Hoodie",
  "Annaki Polpo-Pic Tank",
  "Apex Sweater",
  "Apple Ringer",
  "Arctic Monster Parka",
  "Armor Jacket Replica",
  "Astro Wear",
  "B-ball Jersey (Away)",
  "B-ball Jersey (Home)",
  "Baby-Jelly Shirt",
  "Barazushi Anorak",
  "Barazushi Black Tee",
  "Barazushi Rice Tee",
  "Barazushi Sakura Tee",
  "Barazushi Tuff Duffel",
  "Barazushi Wrap",
  "Base White Button Up",
  "Baseball Jersey",
  "Basic Tee",
  "Berry BlobMob Tee",
  "Berry Ski Jacket",
  "Black 8-Bit FishFry",
  "Black Anchor Tee",
  "Black Baseball LS",
  "Black Inky Rider",
  "Black Layered LS",
  "Black LS",
  "Black Polo",
  "Black Squideye",
  "Black Tee",
  "Black V-Neck Tee",
  "Blue Peaks Tee",
  "Blue Retro Tee",
  "Blue Sailor Suit",
  "Business Animal",
  "Button-Clown Shirt",
  "Camo Layered LS",
  "Camo Zip Hoodie",
  "Carnivore Tee",
  "Chaos Commander Suit",
  "Chili Octo Aloha",
  "Choco Layered LS",
  "Cream Tundra Fleece",
  "Crimson Parashooter",
  "Crispy Crustume",
  "Cycle King Jersey",
  "Cycling Shirt",
  "Dark Bomber Jacket",
  "Dark Urban Vest",
  "Distressed Vest",
  "Duskwave Tee",
  "Dustcloud Hoodie",
  "Dusty Field Jacket",
  "Eelzebub Tee",
  "Enchanted Robe A",
  "Enchanted Robe B",
  "Fancyfish Stitch",
  "Fashion Splash Shirt",
  "FC Albacore",
  "Firefin Navy Sweat",
  "Firewave Tee",
  "Forest Vest",
  "Forge Inkling Parka",
  "Forge Octarian Jacket",
  "Fresh Fish Gloves",
  "Fugu Tee",
  "Grape Tee",
  "Gray College Sweat",
  "Gray Hoodie",
  "Gray Mixed Shirt",
  "Gray Vector Tee",
  "Green-Check Shirt",
  "Green Cardigan",
  "Green Striped LS",
  "Green Tee",
  "Green Zip Hoodie",
  "Herbivore Tee",
  "Hero Jacket Replica",
  "Hero Suit Replica",
  "Hula Punk Shirt",
  "Icewave Tee",
  "Ink-Black Paddle Jack",
  "Ink-Black Tangle Top",
  "Ink-Wash Shirt",
  "Inkfall Shirt",
  "Ivory Peaks Tee",
  "Juice Parka",
  "Kensa Coat",
  "Khaki Ranger Vest",
  "Krak-On 528",
  "Layered Anchor LS",
  "Layered Vector LS",
  "Lemon Hoodless",
  "Light-Bright Paddle Jack",
  "Lime Battlecrab Shell",
  "Lime BlobMob Tee",
  "Lime Ski Jacket",
  "Linen Shirt",
  "Logo Aloha Shirt",
  "Lumberjack Shirt",
  "Manatee Swag Sweat",
  "Marinated Top",
  "Matcha Down Jacket",
  "Mint Tee",
  "Moby Knit",
  "Motley Hoodless",
  "Mountain Vest",
  "N-Pacer Sweat",
  "Navy College Sweat",
  "Navy Striped LS",
  "Navy Z+F Tee",
  "Negative Longcuff Sweater",
  "Octo Jumper Away",
  "Octo Tee",
  "Octobowler Shirt",
  "Octosquid Tandem Tee",
  "Olive Ski Jacket",
  "Orange Cardigan",
  "Orca Bolero",
  "Part-Time Pirate",
  "Patchwork Bomber",
  "Pearl Tee",
  "Pearlescent Hoodie",
  "Penguin Bolero",
  "Pineapple Ringer",
  "Pirate-Stripe Tee",
  "Power Armor Mk I",
  "Power Armor",
  "Purple Camo LS",
  "Rad Plaid Casual",
  "Rainy-Day Tee",
  "Red-Check Shirt",
  "Red Battlecrab Shell",
  "Red Vector Tee",
  "Reel Sweat",
  "Reggae Tee",
  "Retro Gamer Jersey",
  "Retro Sweat",
  "Rockenberg Black",
  "Rockenberg White",
  "Rodeo Shirt",
  "Round-Collar Shirt",
  "Rugby King 08",
  "Rugby King 10",
  "Sailor-Stripe Tee",
  "Sage Polo",
  "Samurai Jacket",
  "School Cardigan A",
  "School Cardigan B",
  "School Jersey",
  "School Uniform A",
  "School Uniform B",
  "Schoolyard Scrap Jack",
  "Seafoam Hoodie",
  "Seahorse Shoreliner",
  "Shirt & Tie",
  "Shrimp-Pink Polo",
  "Sky-Blue Squideye",
  "Slipstream United",
  "Splatfest Tee",
  "Squid Satin Jacket",
  "Squid-Pattern Waistcoat",
  "Squid-Stitch Tee",
  "Squiddor Polo",
  "Squidmark LS",
  "Squidmark Sweat",
  "Squidstar Waistcoat",
  "Squinja Suit",
  "Steel Platemail",
  "Striped Peaks LS",
  "Striped Rugby",
  "Striped Shirt",
  "Sudadera Celeste",
  "Sudadera Roja",
  "Sunny-Day Tee",
  "Takoroka Galactic Tie Dye",
  "Takoroka Nylon Vintage",
  "Takoroka Rainbow Tie Dye",
  "Tan Retro Tee",
  "Tentatek Tandem",
  "Tri-Octo Tee",
  "Tri-Shred Tee",
  "Tri-Squid Tee",
  "Tricolor Rugby",
  "Trooper Top",
  "Umibozu Home Jersey",
  "Urban Upcycle Top",
  "Urchins Jersey",
  "Vaporwave Tee",
  "Varsity Baseball LS",
  "Varsity Jacket",
  "Vintage Check Shirt",
  "White 8-Bit FishFry",
  "White Anchor Tee",
  "White Baseball LS",
  "White Inky Rider",
  "White King Tank",
  "White Layered LS",
  "White LS",
  "White Sailor Suit",
  "White Shirt",
  "White Striped LS",
  "White Tee",
  "White V-Neck Tee",
  "White Z+F Tee",
  "Yellow Layered LS",
  "Yellow Urban Vest",
  "Zapfish Satin Jacket",
  "Zekko Baseball LS",
  "Zekko Hoodie",
  "Zink Layered LS",
  "Zink LS",
  "Commander Tunic",
  "White Retro Tee",
  "Takoroka Tandem",
  "Lyco-P Streetstyle Tee",
  "Annaki Anchored Coat",
  "Indigo Boss Haori",
  "Takoroka Nineties Nylon",
  "Umibozu Road Jersey",
  "Hype Stripe Button Up",
  "Black Ranger Vest",
  "Retro Future Suit",
  "Takoroka \\m/ Crab",
  "Takoroka \\m/ Alien",
  "Plum Barazushi Wrap",
  "King Mesh Tee",
  "Lime Hoodless",
  "Dark Distressed Vest",
  "Garden Gear",
  "Crustwear XXL",
  "Brinestone Jacket"
];


const shoes = [
  "Acerola Rain Boots",
  "Angry Rain Boots",
  "Annaki Habaneros",
  "Annaki Tigers",
  "Arctic Duck Boots",
  "Armor Boot Replicas",
  "Arrow Pull-Ons",
  "Arrow Toesies Blu",
  "Baggy-Sock Fringe Loafs",
  "Banana Basics",
  "Base Fringed Loafers",
  "Base School Shoes",
  "Black Flip-Flops",
  "Black Seahorses",
  "Black Trainers",
  "BlobMob Flip-Flops",
  "Blu-Shift Moto Boots",
  "Blue & Black Squidkid IV",
  "Blue Lo-Tops",
  "Blue Moto Boots",
  "Blue Sea Slugs",
  "Blue Shrimpsiders",
  "Blue Slip-Ons",
  "Blueberry Casuals",
  "Bubble Rain Boots",
  "Chaos Kicks",
  "Cherry Kicks",
  "Choco Clogs",
  "Chocolate Dakroniks",
  "Clownfish Basics",
  "Crazy Arrows",
  "Cream Hi-Tops",
  "Custom Trail Boots",
  "Cuttlefish Sandies",
  "Cyan Dadfoot Sandals",
  "Cyan Trainers",
  "Dark-Roast Boaties",
  "Desert Chukkas",
  "Dustcloud Hi-Tops",
  "E-JECT 30XX",
  "Enchanted Boots",
  "Force ReBoots",
  "Fresh Fish Feet",
  "Fry Tops",
  "Fuzzy Boots",
  "Gold Hi-Horses",
  "Green Rain Boots",
  "Green Toejamz",
  "Hero Boot Replicas",
  "Hero Runner Replicas",
  "Hunter Hi-Tops",
  "Hunting Boots",
  "Ink-Black Clam 600s",
  "Kick Dampeners",
  "Kid Clams",
  "Knotty Bois",
  "LE Soccer Shoes",
  "LE Lo-Tops",
  "Luminous Delta Straps",
  "Mako Bucket Hi-Tops",
  "Marinated Slip-Ons",
  "Mawcasins",
  "Moto Boots",
  "Navy Red-Soled Wingtips",
  "Navy Toejamz",
  "Neon Delta Straps",
  "Neon Sea Slugs",
  "Onyx 01STERs",
  "Orange Arrows",
  "Orange Dadfoot Sandals",
  "Orange Lo-Tops",
  "Oyster Clogs",
  "Pearl 01STERs",
  "Pearlescent Kicks",
  "Pink Dadfoot Sandals",
  "Pink Trainers",
  "Plum Casuals",
  "Power Boots Mk I",
  "Power Boots",
  "Punk Cherries",
  "Punk Nights",
  "Punk Pinks",
  "Punk Whites",
  "Punk Yellows",
  "Purple Hi-Horses",
  "Purple Sea Slugs",
  "Red & Black Squidkid IV",
  "Red & White Squidkid V",
  "Red 3-Straps",
  "Red FishFry Sandals",
  "Red Hammertreads",
  "Red Hi-Horses",
  "Red Hi-Tops",
  "Red Toejamz",
  "Red Sea Slugs",
  "Red Slip-Ons",
  "Red Work Boots",
  "Roasted Brogues",
  "Samurai Shoes",
  "School Shoes + Hi Socks",
  "Seafoam Hi-Tops",
  "Shark Moccasins",
  "Skipjack Work Boots",
  "Slamgerine Slip-Ons",
  "Snow Delta Straps",
  "Snowy Down Boots",
  "Soccer Shoes",
  "Squid-Stitch Slip-Ons",
  "Squinja Boots",
  "Squink Wingtips",
  "Steel Greaves",
  "Suede Basics",
  "Suede Bosses",
  "Sunny Climbing Shoes",
  "Sunset Orca Hi-Tops",
  "Tan Work Boots",
  "Tenya OctoReds",
  "Trail Boots",
  "Transom Note Boots",
  "Turbo Tabi Red",
  "Turquoise Kicks",
  "U Jellys",
  "Wasabi Tabi",
  "White 3-Straps",
  "White Arrows",
  "White Clam 600s",
  "White Kicks",
  "White Seahorses",
  "Yellow FishFry Sandals",
  "Yellow Seahorses",
  "Yellow Toejamz",
  "Zebrafish Hi-Tops",
  "ZedFry Slip-Ons",
  "Zombie Hi-Horses",
  "Tenya OctoPurps",
  "White Lo-Vert Hi-Tops",
  "Hyper Guppies",
  "Arrow Toesies Purp",
  "Annaki Strappy Sandals",
  "Pro Trail Boots",
  "Icy Down Boots",
  "Dappled Hammerheads",
  "Blue & Black Squidkid III",
  "Red & White Squidkid III",
  "Squid Bone Unslips",
  "Field Duck Boots",
  "Red-Shift Moto Boots",
  "Nonslip Senseis",
  "Flipper Floppers",
  "Brinestone Boots"
];


const weaponElement = document.getElementById("weapon");
const headgearElement = document.getElementById("headgear");
const shirtElement = document.getElementById("shirt");
const shoeElement = document.getElementById("shoe");
const randomizeButton = document.getElementById("randomize-button");
const closeButton = document.getElementById('close-button');
const patchnotescloseButton = document.getElementById('patch-notes-close-button');
const patchnotesCard = document.querySelector('.patch-notes-card');
const patchnotesButton = document.getElementById('patch-notes-button');
const optionsCard = document.querySelector('.options-card');
const optionsButton = document.getElementById('options-button');
const hideAmiiboGear = document.getElementById("hide-amiibo-gear");
const hideAmiiboGearCheckbox = document.getElementById("hide-amiibo-gear");

// Load the option value from localStorage if it exists
const hideAmiiboGearOption = localStorage.getItem("hideAmiiboGearOption");
if (hideAmiiboGearOption !== null) {
  hideAmiiboGearCheckbox.checked = JSON.parse(hideAmiiboGearOption);
}

// Listen for changes to the checkbox and save the value to localStorage
hideAmiiboGearCheckbox.addEventListener("change", () => {
  localStorage.setItem("hideAmiiboGearOption", hideAmiiboGearCheckbox.checked);
});

patchnotesButton.addEventListener("click", function() {
  // Toggle the display property of the patch notes card
  if (patchnotesCard.style.display === "none") {
    patchnotesCard.style.display = "block";
  } else {
    patchnotesCard.style.display = "none";
  }
});

optionsButton.addEventListener("click", function() {
  // Toggle the display property of the options card
  if (patchnotesCard.style.display === "none") {
    optionsCard.style.display = "block";
  } else {
    optionsCard.style.display = "none";
  }
});

patchnotescloseButton.addEventListener('click', function() {
  patchnotesCard.style.display = "none";
});

closeButton.addEventListener('click', function() {
  optionsCard.style.display = "none";
});

function randomize() {
  const randomweapon = weapons[Math.floor(Math.random() * weapons.length)];
  let randomheadgear, randomshirt, randomshoe;
  
  // Check if "Hide amiibo gear" is checked and filter out unwanted gear
  if (hideAmiiboGear.checked) {
    const filteredHeadgears = headgears.filter(gear => {
      return ![
        "Boss Floss",
        "Chaos Helm",
        "Enchanted Hat",
        "Fresh Fish Head",
        "Marinated Headphones",
        "Pearlescent Crown L",
        "Pearlescent Crown S",
        "Power Mask Mk I",
        "Power Mask",
        "Samurai Helmet",
        "Squid Clip-Ons",
        "Squid Hairclip",
        "Squinja Mask Mk I",
        "Squinja Mask Mk II",
        "Steel Helm",
        "Sushi Sous-Chef Band",
        "Armor Helmet Replica",
        "Hero Headset Replica"
      ].includes(gear);
    });
    const filteredShirts = shirts.filter(gear => {
      return ![
        "Black-Belt Gi",
        "Chaos Commander Suit",
        "Enchanted Robe A",
        "Enchanted Robe B",
        "Fresh Fish Gloves",
        "Marinated Top",
        "Pearlescent Hoodie",
        "Power Armor Mk I",
        "Power Armor",
        "Samurai Jacket",
        "School Cardigan A",
        "School Cardigan B",
        "School Uniform A",
        "School Uniform B",
        "Schoolyard Scrap Jack",
        "Squinja Suit",
        "Steel Platemail",
        "Armor Jacket Replica",
        "Hero Jacket Replica"
      ].includes(gear);
    });
    const filteredShoes = shoes.filter(gear => {
      return ![
        "Baggy-Sock Fringe Loafs",
        "Base Fringed Loafers",
        "Base School Shoes",
        "Chaos Kicks",
        "Enchanted Boots",
        "Fresh Fish Feet",
        "Kick Dampeners",
        "Knotty Bois",
        "Marinated Slip-Ons",
        "Pearlescent Kicks",
        "Power Boots Mk I",
        "Power Boots",
        "Samurai Shoes",
        "School Shoes + Hi Socks",
        "Squinja Boots",
        "Steel Greaves",
        "Armor Boot Replicas",
        "Hero Runner Replicas"
      ].includes(gear);
    });
    randomheadgear = filteredHeadgears[Math.floor(Math.random() * filteredHeadgears.length)];
    randomshirt = filteredShirts[Math.floor(Math.random() * filteredShirts.length)];
    randomshoe = filteredShoes[Math.floor(Math.random() * filteredShoes.length)];
  } else {
    randomheadgear = headgears[Math.floor(Math.random() * headgears.length)];
    randomshirt = shirts[Math.floor(Math.random() * shirts.length)];
    randomshoe = shoes[Math.floor(Math.random() * shoes.length)];
  }
  
  weaponElement.textContent = randomweapon;
  headgearElement.textContent = randomheadgear;
  shirtElement.textContent = randomshirt;
  shoeElement.textContent = randomshoe;
}

const tweetButton = document.getElementById("tweet-button");
tweetButton.addEventListener("click", function() {
  const weapon = document.getElementById("weapon").textContent;
  const headgear = document.getElementById("headgear").textContent;
  const shirt = document.getElementById("shirt").textContent;
  const shoe = document.getElementById("shoe").textContent;
  const tweetMessage = `I just generated a random weapon & outfit using the #Splatoon3 Randomizer!\n\nResults:\nWeapon - ${weapon}\nHeadgear - ${headgear}\nShirt - ${shirt}\nShoes - ${shoe}\nhttps://codymkw.github.io/splat3`;
  
      navigator.clipboard.writeText(tweetMessage);
      alert("The message was copied to clipboard now you can go to twitter and post it or you can post it somewhere else it's up to you! :D");
});

randomizeButton.addEventListener('click', () => {
  tweetButton.removeAttribute('disabled');
});

if ("serviceWorker" in navigator) {
  navigator.serviceWorker
    .register("/sw.js")
    .then(serviceWorker => {
      console.log("Service Worker registered: ", serviceWorker);
    })
    .catch(error => {
      console.error("Error registering the Service Worker: ", error);
    });
}

randomizeButton.addEventListener("click", randomize);

   // Get the footer element
   var footer = document.querySelector('footer');

   // Get the start year
   var startYear = 2023; // Replace with the desired start year
   
   // Get the current year
   var currentYear = new Date().getFullYear();
   
   // Build the footer text
   var footerText = '&copy; ' + (startYear === currentYear ? startYear : startYear + ' - ' + currentYear) + ' CodyMKW. All rights reserved.';
   
   // Update the footer text
   footer.innerHTML = footerText;